### ISSUE TITLE
latest ArchivesSpace image is fighting with this

### ISSUE THREAD

**Issue by Blake-** [dts-hosting/aspace-aws-metrics#8]
`Bundler::GemNotFound: Could not find gem 'factory_bot'`

It was happening on releasetest and confirmed on QA.

[qa_log.txt](https://github.com/user-attachments/files/16532983/qa_log.txt)

**Comment by mark-cooper** [comment]
I think the better long term solution for us is: https://github.com/dts-hosting/issues-only/issues/237

Maintaining plugins with Gemfiles can be a hassle, especially when supporting multiple versions of ArchivesSpace.
